#!/usr/bin/env python3
"""Script to create the text generated based on the fifteenth chapter of
Joyce's Ulysses, 'Circe.' It runs along the structure described in the file
/UlyssesRedux/stats/15-stats.psv, which is generated by the utility script
/UlyssesRedux/scripts/util/analyze-chapter-15.py, drawing from multiple
corpora and building a chapter that's based on those multiple corpora in an
outwardly similar form.

A Markov length of 2 seems to work well here, according to insufficient tests
evaluated informally.

This program is licensed under the GPL v3 or, at your option, any later
version. See the file LICENSE.md for a copy of this license.
"""


import glob
import os
import pprint
import sys


sys.path.append('/UlyssesRedux/scripts/')
import directory_structure as ds    # Gets us the listing of file and directory locations.
from chapter_scripts.generic_chapter import train_with_mixins


sys.path.append(ds.markov_generator_path)
import text_generator as tg

# First, set up constants
chain_length = 2
mixin_texts_dir = ds.current_run_corpus_directory / '15'
verbosity = 0


def log_it(what: str,
           minimum_verbosity: int = 1) -> None:
    if verbosity >= minimum_verbosity:
        print(what)


def write_story():
    corpora = dict()
    log_it("INFO: about to start processing corpora.")

    for which_corpus in sorted(list(ds.circe_corpora_path.glob('*txt'))):
        log_it(f'  INFO: processing "{which_corpus}".', 2)
        corpus_name = which_corpus.stem
        genny = tg.TextGenerator(name=f"{corpus_name} generator")
        train_with_mixins(genny, chain_length, [which_corpus], list(mixin_texts_dir.glob('*txt')))
        corpora[corpus_name] = genny

    log_it("DEBUGGING: Corpora are: \n" + pprint.pformat(corpora), 3)

    the_chapter = list()

    def get_speaker_text(speaker_name: str,
                         num_sentences: int) -> str:
        if speaker_name in corpora:
            which_index = speaker_name
        elif speaker_name == 'STAGE':
            which_index = 'STAGE DIRECTIONS'
        else:
            which_index = 'MINOR CHARACTERS'
        return corpora[which_index].gen_text(sentences_desired=num_sentences, paragraph_break_probability=0)

    log_it("INFO: About to process stats file.")

    with open(ds.circe_stats_path) as circe_stats_file:
        for the_encoded_paragraph in circe_stats_file:
            # Process each line, using it as a map of the corresponding paragraph in 'Circe'.
            # Structure of these lines is defined in /UlyssesRedux/scripts/util/analyze-chapter-15.py.
            # But here's a quick reminder:
            # Two parts: first, the name of a speaker (or "STAGE" if it's a paragraph of stage directions)
            # Then, a series of codes for "chunks" of the paragraph.
            # A "chunk" is a number of sentences. If the number is preceded by opening parens, it's an intraparagraph
            # stage direction. Parts of the line, and chunk descriptions, are separated by vertical bars (pipe
            # characters), hence the .psv extension.

            log_it(f'INFO: Processing coded line "{the_encoded_paragraph.strip()}".', 2)
            code_to_process = the_encoded_paragraph.split('|')
            speaker_name = code_to_process.pop(0)
            log_it(f'  speaker name is "{speaker_name}".', 2)
            if speaker_name != 'STAGE':                         # Unless the name is 'STAGE', add it to the beginning of this paragraph
                this_paragraph = f'{speaker_name}: '
            else:                                               # In which case, begin with an opening parenthesis.
                this_paragraph = '('
            while len(code_to_process) > 0:
                chunk_descriptor = code_to_process.pop(0)
                log_it(f'    processing chunk "{chunk_descriptor.strip()}".', 2)
                if chunk_descriptor[0] == '(':
                    this_paragraph += f"({get_speaker_text('STAGE', int(chunk_descriptor[1:])).strip()}) "
                else:
                    this_paragraph += f'{get_speaker_text(speaker_name, int(chunk_descriptor))} '
                log_it(f'      current paragraph length is now {len(this_paragraph)}.' , 3)
            if speaker_name == 'STAGE':
                this_paragraph = this_paragraph.strip() + ')'
            log_it(f'        done with this paragraph; total length is {len(this_paragraph)}.', 2)
            the_chapter.append(this_paragraph)

    return '\n'.join(the_chapter)


if __name__ == "__main__":
    verbosity = 3
    print(write_story())
