#!/usr/bin/env python3
"""When all 18 chapters of a Ulysses Redux set have been written, run this script
to postprocess the index.html file that's been created.

Currently, this script performs the following actions:
    * Updates the Git repo with currently existing code, then commits the code
      to the current branch of the Git repository.
    * Updates the coding journal on the UlyssesRedux web space on my personal
      website.
    * Transforms the HTML fragment index.html, which is generated by the
      multiple runs of daily_script.py, into a full-fledged table-of-contents
      file, then puts that file with an appropriate name in the directory
      /~patrick/projects/UlyssesRedux/contents, which is the local directory
      from which it will be synced to my actual website.
      * In order to do so, it reads the file /UlyssesRedux/current-run/data.csv
        and looks for data about the current run there. What it can't find, it
        prompts for.
    * Adds an index line to the meta- (master) table of contents at
      /~patrick/projects/UlyssesRedux/contents/index.html.
    * Syncs the modified local website copy to the website. Note that this syncs
      the entire local copy of my website to the server, not just the Ulysses
      Redux content (and so I sometimes say 'no' if there are other, incomplete
      changes in process).
    * Sets up the next run (by running setup-run.py).
For most (all?) of these actions, explicit user confirmation is requested before
the action is actually performed.

This program is licensed under the GPL v3 or, at your option, any later
version. See the file LICENSE.md for a copy of this licence.
"""


import datetime
import glob
import os
import subprocess
import sys
import time

from typing import Optional
from pathlib import Path

sys.path.append('/UlyssesRedux/scripts/')
from util.current_run_utils import confirm
import util.setup_run as sr

from directory_structure import *           # Gets us the listing of file and directory locations.
import util.current_run_utils as cru


# global variables
debugging = True

CURRENT_EPISODE_NUMBER: Optional[int] = None
current_run_data: Optional[dict] = None
html_file: Optional[str] = None

current_git_branch = cru.get_current_git_branch()


def set_up_git() -> None:
    """# All right, let's sync the data to the folder that actually maintains the Git repository, If desired
    """
    global current_git_branch

    # First, get basic info about the current git branch that we'll need later even if not syncing.
    oldpath = os.getcwd()       # FIXME! do we even need this and the try/finally now that the current git branch is checked in cru.current_git_branch() instead of here?
    try:
        os.chdir(git_repo_path)

        print(f"\n\nCurrent git branch is:\n   {current_git_branch}")
        if not confirm('update Git repo with changed code files in this branch? '):
            return

        subprocess.check_call(['git', 'add', '-u'])
        current_git_status = subprocess.check_output(['git', 'status'])
        print(f"Current git status is\n  {current_git_status.decode()}")        # Check: do those two spaces after \n make sense?

        if not confirm('GIVEN THIS STATUS, do you want to commit? '):
            return

        subprocess.call(['git', 'commit'])
        if not confirm('Push branch %s to remote server? ' % current_git_branch):
            return

        subprocess.check_call(['git', 'push', 'origin', current_git_branch])
        if not confirm('Switch to master branch and merge these changes? '):
            return

        print('\n')
        subprocess.check_call(['git', 'checkout', 'master'])
        subprocess.check_call(['git', 'merge', current_git_branch])
        print("\nWARNING: THE MASTER BRANCH IS NOW THE CURRENT BRANCH\n")

        if not confirm('Push master branch to remote server? '):
            return

        subprocess.check_call(['git', 'push', 'origin', 'master'])

    finally:
        os.chdir(oldpath)

    if debugging: print("\n\nINFO: Git work done, beginning to generate HTML table of contents")


def set_up() -> None:
    global CURRENT_EPISODE_NUMBER, current_run_data

    if debugging:
        print("INFO: imports successful.")

    CURRENT_EPISODE_NUMBER = 1 + int(str(sorted(list(webpage_contents_directory.glob('???.html')))[-1])[-8:-5])

    # All right, let's read the expected data from the data file
    cru.validate_data()
    current_run_data = cru.read_current_run_parameters()

    if debugging:
        print("INFO: parameters read in and calculated.")

    set_up_git()


def get_html_header() -> str:
    return f"""<!doctype html>
<html prefix="og: http://ogp.me/ns#" xml:lang="en" lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" type="text/css" href="/~patrick/css/min.css" />
  <link rel="stylesheet" type="text/css" href="/~patrick/css/content.css" />
  <link rel="meta" type="application/rdf+xml" title="FOAF" href="/~patrick/foaf.rdf" />
  <meta name="foaf:maker" content="foaf:mbox_sha1sum '48a3091d919c5e75a5b21d2f18164eb4d38ef2cd'" />
  <link rel="profile" href="http://microformats.org/profile/hcard" />
  <link rel="profile" href="http://microformats.org/profile/hcalendar" />
  <link rel="profile" href="http://gmpg.org/xfn/11" />
  <link rel="pgpkey" type="application/pgp-keys" href="/~patrick/505AB18E-public.asc" />
  <link rel="home" href="/~patrick/" title="Home page" />
  <link href="/~patrick/feeds/updates.xml" type="application/atom+xml" rel="alternate" title="Sitewide ATOM Feed" />
  <link rel="home" href="/~patrick/projects/UlyssesRedux/" title="Home page" />
  <link rel="icon" type="image/x-icon" href="/~patrick/icons/favicon.ico" />
  <link rel="contents" href="/~patrick/projects/UlyssesRedux/contents/" />
  <link rel="start" href="001.html" />
  <link rel="prev" href="{(CURRENT_EPISODE_NUMBER - 1):03}.html" />
  <link rel="next" href="{(CURRENT_EPISODE_NUMBER + 1):03}.html" />

  <title>Ulysses Redux #{CURRENT_EPISODE_NUMBER:03}</title>
  <meta name="generator" content="https://github.com/patrick-brian-mooney/UlyssesRedux/blob/master/utility_scripts/postprocess-set.py" />
  <meta name="author" content="Patrick Mooney" />
  <meta name="dcterms.rights" content="Copyright © 2015&ndash;26 Patrick Mooney" />
  <meta name="description" content="Table of contents for Ulysses Redux #{CURRENT_EPISODE_NUMBER:03}" />
  <meta name="rating" content="general" />
  <meta name="revisit-after" content="10 days" />

  <meta name="date" content="{time.strftime("%Y-%m-%dT%H:%M:%S")}" />
  <meta property="fb:admins" content="100006098197123" />
  <meta property="og:url" content="http://patrickbrianmooney.nfshost.com/~patrick/projects/UlyssesRedux/contents/{CURRENT_EPISODE_NUMBER:03}.html" />
  <meta property="og:title" content="Ulysses Redux #{CURRENT_EPISODE_NUMBER:03}" />
  <meta property="og:description" content="Table of contents for Ulysses Redux #{CURRENT_EPISODE_NUMBER:03}" />
  <meta property="og:locale" content="en_US" />
  <meta property="og:site_name" content="Patrick Mooney's web site" />
  <meta property="og:image" content="http://patrickbrianmooney.nfshost.com/~patrick/icons/gear-large.png" />
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@patrick_mooney" />
  <meta name="twitter:creator" content="@patrick_mooney" />
  <meta name="twitter:title" content="Ulysses Redux #{CURRENT_EPISODE_NUMBER:03}" />
  <meta name="twitter:description" content="Table of contents for Ulysses Redux #{CURRENT_EPISODE_NUMBER:03}" />
  <meta name="twitter:image:src" content="http://patrickbrianmooney.nfshost.com/~patrick/icons/gear-large.png" />
</head>
"""


def get_summary_fragment() -> str:
    """Get a summary fragment and turn it into valid HTML, if it isn't already.
    Assumption: if the fragment as a whole is bracketed <p> ... </p>, assume it's a
    pre-formatted HTML fragment; otherwise, split it into lines and bracket those
    lines with <p> ... </p>.
    """
    if current_run_data['summary'].startswith('<p>') and current_run_data['summary'].endswith('</p>'):
        summary_text = current_run_data['summary']
    else:
        summary_text = '\n'.join(['<p>' + the_line.strip() + '</p>' for the_line in current_run_data['summary'].split('\n')])

    return f"""
    <h2 id="summary">Summary</h2>

    {summary_text}
    """


def get_contents_fragment() -> str:
    return f"""\n\n<h2 id="toc">Contents</h2>\n\n<ol>\n{open(toc_fragment).read()}\n</ol>"""


def get_scripts_fragment() -> str:
    return f"""<h2 id="scripts">Scripts</h2>

<p>The scripts used to generate this edition of <cite class="book-title">Ulysses Redux</cite> are available <a rel="me" href="{(github_branch_base_path + current_git_branch)}">here</a>.</p>\n\n"""


def get_ending_fragment() -> str:
    return f"""<footer class="status vevent vcard"><a class="url location" href="#">This web page</a> is copyright © {time.strftime("%Y")} by <a rel="me" href="/~patrick/" class="fn url">Patrick Mooney</a>. <abbr class="summary description" title="Last update to table of contents for Ulysses Redux #{CURRENT_EPISODE_NUMBER:03}">Last update to <a class="url" href="#">this HTML file</a></abbr>: <abbr class="dtstart" title="{time.strftime("%Y-%m-%dT%H:%M:%S")}">{time.strftime("%d %B %Y")}</abbr>.</footer>

</div>\n</body>\n</html>
"""


def get_html_page() -> str:
    return f"""{get_html_header()}
<body lang="en-US" xml:lang="en-US"><div class="container">

<!--Begin navigation and tracking code-->
<header id="main-nav">
  <script type="text/javascript" src="/~patrick/nav.js"></script>
  <noscript>
    <p class="simpleNav"><a rel="me home" href="index.html">Go home</a></p>
    <p class="simpleNav">If you had JavaScript turned on, you'd have more navigation options.</p>
  </noscript>
</header>
<!--end navigation and tracking code -->

<h1>Ulysses Redux #{CURRENT_EPISODE_NUMBER:03}: {current_run_data['current-run-name']}</h1>

{get_summary_fragment()}

{get_contents_fragment()}

{get_scripts_fragment()}

{get_ending_fragment()}
"""


def check_update_coding_journal() -> None:
    """Check whether the user wants to update the coding journal, and if so, do it.
    """
    if not confirm('Update coding journal on website? '):
        return

    subprocess.call(["pandoc", "-f", "markdown", "-s", "-t", "html5", "-o",
                     '/~patrick/projects/UlyssesRedux/coding.html', '/UlyssesRedux/coding thoughts.md'])
    text = Path('/~patrick/projects/UlyssesRedux/coding.html').read_text(encoding='utf-8').split('<body>')
    html_content = f"""
<!doctype html>
<html prefix="og: http://ogp.me/ns#" xml:lang="en" lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <meta charset="utf-8" />
  <link rel="stylesheet" type="text/css" href="/~patrick/css/min.css" />
  <link rel="stylesheet" type="text/css" href="/~patrick/css/content.css" />
  <link rel="meta" type="application/rdf+xml" title="FOAF" href="/~patrick/foaf.rdf" />
  <meta name="foaf:maker" content="foaf:mbox_sha1sum '48a3091d919c5e75a5b21d2f18164eb4d38ef2cd'" />
  <link rel="profile" href="http://gmpg.org/xfn/11" />
  <link rel="pgpkey" type="application/pgp-keys" href="/~patrick/505AB18E-public.asc" />
  <link rel="author" href="http://plus.google.com/109251121115002208129?rel=author" />
  <link rel="home" href="/~patrick/projects/UlyssesRedux" title="Home page" />
  <link rel="icon" type="image/x-icon" href="/~patrick/icons/favicon.ico" />
  <link href="/~patrick/feeds/updates.xml" type="application/atom+xml" rel="alternate" title="Sitewide ATOM Feed" />

  <title>Ulysses Redux Coding Notes</title>
  <meta name="generator" content="https://github.com/patrick-brian-mooney/UlyssesRedux/blob/master/utility_scripts/postprocess-set.py" />
  <meta name="author" content="Patrick Mooney" />
  <meta name="dcterms.rights" content="Copyright © 2015–{datetime.datetime.now().year} Patrick Mooney" />
  <meta name="description" content="Coding notes for Ulysses Redux, blog of auto-generated text based on Joyce's Ulysses" />
  <meta name="rating" content="general" />
  <meta name="revisit-after" content="10 days" />
  <meta name="date" content="{datetime.datetime.now().isoformat()}" />
  <meta property="fb:admins" content="100006098197123" />
  <meta property="og:url" content="http://patrickbrianmooney.nfshost.com/~patrick/projects/UlyssesRedux/coding.html" />
  <meta property="og:title" content="Ulysses Redux Coding Notes" />
  <meta property="og:description" content="Coding notes for Ulysses Redux, blog of auto-generated text based on Joyce's Ulysses" />
  <meta property="og:locale" content="en_US" />
  <meta property="og:site_name" content="Patrick Mooney's web site" />
  <meta property="og:image" content="http://patrickbrianmooney.nfshost.com/~patrick/icons/gear-large.png" />
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@patrick_mooney" />
  <meta name="twitter:creator" content="@patrick_mooney" />
  <meta name="twitter:title" content="Ulysses Redux Coding Notes" />
  <meta name="twitter:description" content="Coding notes for Ulysses Redux, blog of auto-generated text based on Joyce's Ulysses" />
  <meta name="twitter:image:src" content="http://patrickbrianmooney.nfshost.com/~patrick/icons/gear-large.png" />
 </head>

<body lang="en-US" xml:lang="en-US"><div class="container">

<!--Begin navigation code-->
<header id="main-nav">
  <script type="text/javascript" src="/~patrick/nav.js"></script>
  <noscript>
    <p class="simpleNav"><a rel="me home" href="index.html">Go home</a></p>
    <p class="simpleNav">If you had JavaScript turned on, you'd have more navigation options.</p>
  </noscript>
</header>
<!--end navigation code -->

{text[1]}
</div>
</body>
</html>
"""
    Path('/~patrick/projects/UlyssesRedux/coding.html').write_text(html_content, encoding='utf-8')
    subprocess.call(['tidy', '-m', '-i', '-w', '0', '-utf8', '--doctype', 'html5', '--fix-uri', 'true',
                     '--new-blocklevel-tags', 'footer', '--quote-nbsp', 'true', '--preserve-entities', 'yes',
                     '/~patrick/projects/UlyssesRedux/coding.html'])


def check_update_meta_toc() -> None:
    if not confirm('Update meta-TOC on local copy of website? '):
        return

    toc_text = Path(meta_TOC_path).read_text(encoding='utf-8')
    toc_split = toc_text.split('</ol>')  # Works as long as there's only one ordered list in the document

    new_line = f'<li class="vevent"><a class="url location" rel="me muse" href="{CURRENT_EPISODE_NUMBER:03}.html">'
    new_line += f"""<cite class="book-title">{current_run_data['current-run-name']}</cite></a> """
    new_line += f"""(<span class="dtstart">{time.strftime("%Y-%m-%d")}</span>):"""
    new_line += f"""<span class="summary description">{current_run_data['summary']}</span></li>"""

    toc_text = toc_split[0] + new_line + '\n  </ol>\n</section>\n</div>\n</body>\n</html>'
    Path(meta_TOC_path).write_text(toc_text, encoding='utf-8')


if __name__ == "__main__":
    set_up()
    html_file = get_html_page()

    if debugging:
        print(f"INFO Generated HTML file is:\n{html_file}\n")

    the_output_file = Path(webpage_contents_directory) / f'{CURRENT_EPISODE_NUMBER:03}.html'
    the_output_file.write_text(html_file, encoding='utf-8')
    if debugging:
        print("INFO: HTML file written; tidying ...")

    subprocess.call(['tidy', '-m', '-i', '-w', '0', '-utf8', '--doctype', 'html5', '--fix-uri', 'true',
                     '--new-blocklevel-tags', 'footer', '--quote-nbsp', 'true', '--preserve-entities',
                     'yes', str(Path(webpage_contents_directory) / f'{CURRENT_EPISODE_NUMBER:03}.html')])
    if debugging:
        print("\n\nINFO: Tidying done.")

    print('\n')
    check_update_coding_journal()

    check_update_meta_toc()

    if confirm('Sync web page to main site? '):
        # This script lives on my hard drive at ~/.scripts/sync-website.sh
        subprocess.check_call(['sync-to-nfs.sh'])

    print('\n\n')
    if confirm("We're done here. Want to set up the next run? "):
        sr.do_setup_run()

